# Generated by Django 5.1.5 on 2025-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
    ]
